apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
    - image: rurs1991/auth
      context: auth
      sync:
        manual:
          - src: src/***/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
